CREATE TABLE Users (firstname VARCHAR(50), lastname VARCHAR(50),
       username VARCHAR(50), status TINYINT, email VARCHAR(100), passwordHash VARCHAR(255), passwordSalt VARCHAR(255));
GO
CREATE NONCLUSTERED INDEX [IX_NC_Username] ON [dbo].[Users]
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO